import { X, Copy, Check, Download } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import { useState, useRef, useEffect } from 'react';
import { useCanvasStore } from '@/store/useCanvasStore';
import html2canvas from 'html2canvas';
import { jsPDF } from 'jspdf';
import posthog from 'posthog-js';

export function SidePanel() {
    const selectedNode = useCanvasStore((state) => state.selectedNode);
    const setSelectedNode = useCanvasStore((state) => state.setSelectedNode);
    const [copied, setCopied] = useState(false);
    const timeoutRef = useRef<NodeJS.Timeout | null>(null);
    const contentRef = useRef<HTMLDivElement>(null);
    const [isExporting, setIsExporting] = useState(false);

    useEffect(() => {
        return () => {
            if (timeoutRef.current) clearTimeout(timeoutRef.current);
        };
    }, []);

    if (!selectedNode) return null;

    const data = selectedNode.data;

    const handleCopy = () => {
        navigator.clipboard.writeText(data.content || '');
        setCopied(true);
        posthog.capture('artifact_copied', { title: data.label });
        if (timeoutRef.current) clearTimeout(timeoutRef.current);
        timeoutRef.current = setTimeout(() => setCopied(false), 2000);
    };

    const handleExportPDF = async () => {
        if (!contentRef.current) return;
        setIsExporting(true);

        try {
            const canvas = await html2canvas(contentRef.current, {
                scale: 2,
                backgroundColor: '#18181b', // matches zinc-900 background
                logging: false,
                windowWidth: contentRef.current.scrollWidth,
                windowHeight: contentRef.current.scrollHeight,
            });

            const imgData = canvas.toDataURL('image/png');

            // A4 size: 210 x 297 mm
            const pdf = new jsPDF('p', 'mm', 'a4');
            const pdfWidth = pdf.internal.pageSize.getWidth();
            const pdfHeight = pdf.internal.pageSize.getHeight();

            // Margins
            const margin = 15;
            const imgWidth = pdfWidth - (margin * 2);

            // Calculate corresponding image height to maintain aspect ratio
            const imgHeight = (canvas.height * imgWidth) / canvas.width;

            // Setup coordinates
            let heightLeft = imgHeight;
            let position = margin;
            let pageHeight = pdfHeight - (margin * 2) - 10; // Extra 10mm for watermark

            // Add first page
            pdf.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);

            // Add watermark to first page
            pdf.setFontSize(8);
            pdf.setTextColor(150, 150, 150);
            pdf.text("Generated by the Agentic GTM Canvas | Engineered by Alankrit", pdfWidth / 2, pdfHeight - 10, { align: "center" });

            heightLeft -= pageHeight;

            // Add subsequent pages if content overflows
            while (heightLeft >= 0) {
                position = heightLeft - imgHeight + margin;
                pdf.addPage();
                pdf.addImage(imgData, 'PNG', margin, position, imgWidth, imgHeight);
                pdf.text("Generated by the Agentic GTM Canvas | Engineered by Alankrit", pdfWidth / 2, pdfHeight - 10, { align: "center" });
                heightLeft -= pageHeight;
            }

            pdf.save(`${data.label || 'gtm_artifact'}.pdf`);
            posthog.capture('artifact_exported', { title: data.label });

        } catch (error) {
            console.error('Failed to export PDF', error);
        } finally {
            setIsExporting(false);
        }
    };

    return (
        <AnimatePresence>
            <motion.div
                initial={{ x: "100%", opacity: 0 }}
                animate={{ x: 0, opacity: 1 }}
                exit={{ x: "100%", opacity: 0 }}
                transition={{ type: "spring", stiffness: 300, damping: 30 }}
                className="absolute top-0 right-0 h-full w-[500px] z-50 shadow-2xl backdrop-blur-md bg-zinc-950/95 border-l border-emerald-500/20 flex flex-col"
            >
                <div className="flex items-center justify-between border-b border-zinc-800/80 px-6 py-4 bg-zinc-900/50">
                    <h3 className="text-lg font-bold text-zinc-100">{data.label || 'Execution Artifact'}</h3>
                    <div className="flex items-center gap-2">
                        <button
                            onClick={handleExportPDF}
                            disabled={isExporting}
                            className="flex items-center gap-2 px-3 py-1.5 text-xs font-medium text-emerald-100 bg-emerald-600 hover:bg-emerald-500 rounded-md transition-colors disabled:opacity-50"
                        >
                            <Download className="h-4 w-4" />
                            {isExporting ? 'Exporting...' : 'Export'}
                        </button>
                        <button
                            onClick={handleCopy}
                            className="flex items-center gap-2 px-3 py-1.5 text-xs font-medium text-emerald-400 bg-emerald-500/10 hover:bg-emerald-500/20 rounded-md transition-colors"
                        >
                            {copied ? <Check className="h-4 w-4" /> : <Copy className="h-4 w-4" />}
                            {copied ? 'Copied' : 'Copy'}
                        </button>
                        <button
                            onClick={() => setSelectedNode(null)}
                            className="p-1.5 text-zinc-400 hover:text-white hover:bg-zinc-800 rounded-md transition-colors"
                        >
                            <X className="h-5 w-5" />
                        </button>
                    </div>
                </div>

                <div className="flex-1 overflow-y-auto no-scrollbar p-6">
                    <div ref={contentRef} className="prose prose-invert prose-emerald max-w-none prose-h3:text-lg prose-h3:mt-6 prose-h3:mb-3 prose-p:leading-relaxed prose-p:text-zinc-300 prose-ul:text-zinc-300 prose-strong:text-emerald-100 prose-a:text-emerald-400 bg-zinc-950 p-2">
                        <ReactMarkdown
                            components={{
                                h3: ({ node, ...props }) => <h3 className="text-emerald-400 border-b border-emerald-500/20 pb-2 mb-4" {...props} />,
                                code: ({ node, className, children, ...props }) => {
                                    const match = /language-(\w+)/.exec(className || '')
                                    return (
                                        <code className="bg-zinc-900 px-1.5 py-0.5 rounded-md text-emerald-300 font-mono text-sm" {...props}>
                                            {children}
                                        </code>
                                    )
                                },
                                pre: ({ node, ...props }) => (
                                    <pre className="bg-zinc-900 p-4 rounded-lg border border-zinc-800 my-4 overflow-x-auto" {...props} />
                                )
                            }}
                        >
                            {data.content || '*No content generated.*'}
                        </ReactMarkdown>
                    </div>
                </div>
            </motion.div>
        </AnimatePresence>
    );
}
